### ISSUE TITLE
Please, ship es2015 version

### ISSUE THREAD

**Issue by mkozhukharenko** [sindresorhus/plur#18]
The version of uglify I'm using using doesn't support es6 and the node_modules is not compiles. So I'm getting error `SyntaxError: Unexpected token: operator (>) [./~/plur/index.js:4,0]` during a builds.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
