### ISSUE TITLE
Incorrect plural of media

### ISSUE THREAD

**Issue by Pushplaybang** [sindresorhus/plur#24]
The term media, should not be changed, and remain `media`.

**Comment by sindresorhus** [comment]
Isn't `media` already a plural of `medium` though?

If it is correct, however, it should be added here: https://github.com/sindresorhus/irregular-plurals/blob/master/irregular-plurals.json

**Comment by Pushplaybang** [comment]
I suppose its context specific, 

- one media representative vs many media representatives
- one media outlet vs many media outlets

having a listing for media items, may have the heading media for one or many, along side listings like follower/followers
