### ISSUE TITLE
zero count

### ISSUE THREAD

**Issue by jorisre** [sindresorhus/plur#31]
Hi 👋🏻 

when I pass `0` (zero) as count, `plur` returns the plural form instead of singular. Is it something wanted?

Repro: https://codesandbox.io/s/zen-glade-9vt7ud?file=/src/index.js

Let me know, I can open a PR

**Comment by sindresorhus** [comment]
That's how English works: https://english.stackexchange.com/questions/38293/why-is-zero-followed-by-a-plural-noun
