### ISSUE TITLE
I get a type error on this line:

### ISSUE THREAD

**Issue by ghost** [sindresorhus/plur#32]
For some reason, when I compile the Vite project and ran the `preview` command. 
It throws an error in console and all components become non-functioning.

> `has` method does not exist 

```ts
irregularPlurals.has(word.toLowerCase())
```

So I am unsure what is it. At the moment, since we use only a single word for pluralization, I wrote my own tiny function that will just append `s` for plural meaning. For more complex checks and words, I'd like to use this package, but it's just not working.

**Comment by sindresorhus** [comment]
This is a problem with Vite or your Vite config, not this package. I would ask in the Vite issue tracker instead.

**Comment by strblr** [comment]
@nenadnovakovic-sh Same problem here. Did you find a fix?
