### ISSUE TITLE
Reverse operation

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/plur#33]
As the module already knows how to convert singluar to plural, I wonder if the reverse operation, e.g. convert plural to singular can be supported without much effort. I'd certainly have use cases for it.

**Comment by sindresorhus** [comment]
I don't think this is something I want to support. There's just not much demand for the reverse. I suggest just using a different package if you need that: https://github.com/plurals/pluralize

**Comment by silverwind** [comment]
Ok, thanks for the pointer, it looks suitable.
