### ISSUE TITLE
Incorrectly pluralizes `day` to `daies`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/plur#5]
I think the `.replace(/y$/i, 'ie')` replacement might be a bit too naive.

I don't have the time to look into this now, so help would be much appreciated.

// @therealklanni

**Comment by therealklanni** [comment]
Good point. I think we need to check if there's a vowel preceding the "y", but that may be getting too complex now. (Damn English grammar)

Would you rather remove it or resolve it?

**Comment by therealklanni** [comment]
I'm thinking `.replace(/([^aeiou])y$/i, '$1ie')` (which works, but there may be some weird English grammar edge cases).

I was originally thinking `.replace(/(?:[^aeiou])y$/i, 'ie')` but for whatever reason the replacement wasn't working properly with the non-capturing group.

**Comment by sindresorhus** [comment]
Let's resolve it like you've suggested above. Mind doing a pull request with a couple of tests?
